# Generated by Django 2.0.6 on 2018-06-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='github',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='gitter',
        ),
    ]
