# Generated by Django 2.0.6 on 2018-06-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0002_auto_20180610_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='docs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='gitter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
